import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Footer from "@/components/landing-page/footer";
import { ThemeProvider } from "@/providers/theme-provider";
import Navbar from "@/components/landing-page/hero-section/nav-bar";
import { MusicToggleButton } from "@/components/cool-stuff/music-player";
import { ModeToggle } from "@/components/cool-stuff/light-dark";
import { Particles } from "@/components/ui/particles";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${montserrat.className} antialiased  `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children} <Footer />{" "}
          <div className=" fixed bottom-4 right-4  flex flex-col items-center gap-2 ">
            <ModeToggle />
            <MusicToggleButton />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
